changeLogFile: src/main/resources/liquibase/changelog.xml

#MySQL
#driver: com.mysql.cj.jdbc.Driver
#url: jdbc:mysql://localhost:3306/test_lb?serverTimezone=UTC
#username: root
#password: rootroot


#Postgress
#driver: org.postgresql.Driver
#url: jdbc:postgresql://localhost:5532/test_lb
#username: postgres
#password: postgres


#H2
driver: org.h2.Driver
url: jdbc:h2:mem:test_lb
username: sa
password: sa
