spring.datasource.url=jdbc:mysql://localhost:3306/sec?useUnicode=true&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=rootroot

jwt.header=Authorization
jwt.secret=Zm9vYmFyYmF6cXV4YmF6cXV4YmF6cXV4YmF6cXV4YmF6cXV4YmF6cXV4YmF6cX==
jwt.expiration=600
