spring.application.name=springboot-rabbit
server.port=8089

# rabbit mq
spring.rabbitmq.addresses=amqp://guest:guest@localhost:5672/
# queue
rabbitmq.queue.name=queue
rabbitmq.josn_queue.name=json_queue
# exchange
rabbitmq.exchange.name=xchange
# routing keys
rabbitmq.json_routing_key.name=routing_key
rabbitmq.routing_key.name=routing_key
